"""Write web/js/luts.js: the colour tables of Flowniac.py (build_luts), so both versions use the same colours.

    python web/tools/make_luts.py
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from Flowniac import build_luts  # noqa: E402


def main():
    lut = build_luts()                                       # (3, 256, 3), 0..1
    rows = []
    for name, table in zip(("speed (plasma)", "vorticity", "pressure Cp (RdBu_r)"), lut):
        vals = ",".join(f"{v:.6g}" for v in table.reshape(-1))
        rows.append(f"  // {name}\n  {vals},")
    out = ROOT / "web" / "js" / "luts.js"
    out.write_text(
        "// Generated by web/tools/make_luts.py from Flowniac.build_luts() - do not edit.\n"
        "// Colour tables, 3 x 256 RGB entries (0..1): 0 speed, 1 vorticity, 2 pressure.\n"
        "export const LUTS = new Float32Array([\n" + "\n".join(rows) + "\n]);\n",
        encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
